### ISSUE TITLE
running main.py results in ImportError about 'ParamSpec' in 'typing' module

### ISSUE THREAD

**Issue by jggautier** [michaelbaluja/PyCurator#5]
**Describe the bug**
When I try to run main.py,  I get an ImportError about 'ParamSpec' in 'typing' module. Here's the error message:

```
Traceback (most recent call last):
  File "/Users/juliangautier/Desktop/PyCurator/main.py", line 1, in <module>
    from pycurator.gui import ScraperGUI
  File "/Users/juliangautier/Desktop/PyCurator/pycurator/gui/__init__.py", line 1, in <module>
    from .main import ScraperGUI
  File "/Users/juliangautier/Desktop/PyCurator/pycurator/gui/main.py", line 3, in <module>
    from .MVC import CuratorView, CuratorController
  File "/Users/juliangautier/Desktop/PyCurator/pycurator/gui/MVC.py", line 8, in <module>
    from typing import Optional, ParamSpec, Type, TypeVar, Union
ImportError: cannot import name 'ParamSpec' from 'typing' (/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py)
```

I'm using Python 3.9 and some quick Googling makes me think that ParamSpec works only for Python 3.10, but I'm not sure and would like to avoid updating to 3.10 to test this, although I'd really like to check out this app, so if 3.10 really is a dependency I'll work on updating to 3.10 (or using a virtual environment to switch between Python versions) :)

**To Reproduce**
1. Opened Terminal on my MacOS and downloaded the repository (`git clone https://github.com/michaelbaluja/PyCurator.git`)
2. cd'ed to PyCurator directory
3. Ran `python main.py`
4. Saw ImportError

**Expected behavior**
Depends on whether or not ParamSpec works only for Python 3.10 and later. If it does, maybe the readonly could mention that Python 3.10 or later is needed?

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.6.4
 - Python Version 3.9

**Comment by michaelbaluja** [comment]
@jggautier thanks for bringing this up! You're right that ParamSpec was introduced as of Python 3.10, though for some strange reason this wasn't caught by my interpreter. To avoid upping the requirement to Python 3.10, we've instead imported ParamSpec from the typing_extensions library, and added this to the dependencies list as it is not part of the Python Standard Library. An additional bug from that implementation does however require us to push the Python requirement to >= 3.9.2.
